### ISSUE TITLE
cannot use tk

### ISSUE THREAD

**Issue by dogatana** [arton/RScript22#2]
Hi arton-san,

Thank you for your release of ruby 2.3.1p112.

I downloaded it and tried to use tk, but it showed the error.
Can't we use tk with this release?

> ruby -v  
> ruby 2.3.1p112 (2016-04-26 revision 54768) [i386-mswin32_100] 
> irb  
> irb(main):001:0> require 'tk'  
> LoadError: tcltklib: fail to open tcl_dll 

I appreciate if you could tell me how to use tk.

<added>
I might have misunderstood.
This issue page is for RSCript22, not for ruby2.3..

Regards,
dogatana

**Comment by arton** [comment]
Hi,
Sorry for late response.

Have you already installed ActiveTcl in your box ?
If yes, did you set PATH environment variable points ActiveTcl installed bin directory ?

Or, did you see the popup that shows 'procedure entry point inflateGetHeader ...' ?

Regards

**Comment by arton** [comment]
Hi

I found the resolution.
You should install ActiveTCL 8.5 not 8.6.

Regards

**Comment by dogatana** [comment]
Hi,

Thank you for your reply.

I turned back to Rubyinstaller because I need to use ruby/tk in my business application.
Today I tried again with ActiveTcl 8.5 and TkDND2.8, and they seem to work fine.
(As you wrote, 8.6 didn't work)

Kind Regards
