### ISSUE TITLE
cannot use ScriptControl

### ISSUE THREAD

**Issue by nnkanegon** [arton/RScript22#3]
こんにちは
金子と申します。

Ruby2.3.1(x86)でScriptControlによる呼び出しができないようです。
確認していただけないでしょうか。

sc = new ActiveXObject('ScriptControl');
sc.Language = "RubyScript";
WScript.Echo(sc.Eval("10+20"));

> C:\Windows\SysWOW64\CScript //nologo a.js
> C:\kanegon\a.js(2, 1) ScriptControl: A script engine for the specified language
> can not be created.

なお、HTA経由でのRubyScriptの呼び出しは問題ないようです。

実行環境はWindows 7 64bitですが、
ruby 1.8.7
ruby 2.1.0
ruby 2.1.1
あたりのバージョンではScriptControlは問題なく使用できています。

よろしくお願い致します。

**Comment by arton** [comment]
こんにちは。
レポートありがとうございます。エラーを確認しました。
見てみますが、ちょっと環境の再構築中なので2週間くらいみてください。
よろしくお願いします。

**Comment by arton** [comment]
原因は、ScriptControlが実行するActiveScriptエンジンに対して、初期化（ActiveScriptエンジンの場合はスクリプトのロードに相当すると解釈しています）安全性の保証を求めることでした。
以前のRScriptは、Rubyの$SAFEを利用してそれなりに安全性を考慮していましたが、Ruby2.xから$SAFEが廃止されたため、RSｃriptはロードされるスクリプトの安全性を保証できません。したがって、問い合わせ（IObjectSafetyインターフェイスが利用される）に対してエラーを返します。
以下の安全なActiveControlであるという宣言をRScriptのレジストリ設定に追加すれば動作するようになります（32ビットWindowsの場合は、HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\ClassesをHKEY_CLASS_ROOTに変えてください）。
[HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Classes\CLSID{7DEFB9DD-E95C-4778-B2D8-014C05C69028}\Implemented Categories{7DD95802-9882-11CF-9FA9-00AA006C42C4}]

{7DEFB9DD-E95C-4778-B2D8-014C05C69028} がRScript.2.xのCLSIDです。
7DD95802-9882-11CF-9FA9-00AA006C42C4}]が、CATID_SafeForInitializing（初期化安全性）です。
