### ISSUE TITLE
ActivescriptRuby didn't work

### ISSUE THREAD

**Issue by atbest** [arton/RScript22#4]
I installed ActivescriptRuby from https://www.artonx.org/data/asr/Ruby-2.3.msi, and created a test file test.rb with `puts "Hello";`. Then I ran the command `cscript test.rb`, but got an error message `CScript Error: Can't find script engine "RubyScript" for script "test.rb"`.

My system is windows 7 x64, and I've registered `RScript22.dll` with `regsvr32` successfully, but it didn't help. I still got the same message.

**Comment by arton** [comment]
It seems that you run x64 cscript.exe. Therefore cscript searched x64 active script engine. However,  Rub-2.3.msi is x86 package and was registed  in x86 registory.
I wonder if you could try to run 
c:\windows\syswow64\cscript.exe test.rb

Regards

**Comment by atbest** [comment]
Thanks, this works as expected.
