### ISSUE TITLE
Exception when calling Close on IActiveScript

### ISSUE THREAD

**Issue by manison** [arton/RScript22#5]
When calling `Close` on script engine after a Ruby script finishes, I get an access violation exception from [`Disconnect`](https://github.com/arton/RScript22/blob/master/RScript22/RubyScript.cpp#L882) method. This method internally calls [`remove_items`](https://github.com/arton/RScript22/blob/master/RScript22/lib/activescriptruby.rb#L184) which probably throws a Ruby exception that escapes from the VM.

As I don't know the Ruby and I'm only hosting whatever script engine our users configure, I believe the two things need to be done:
1. Analyze why `remove_items` throws an exception and fix it.
2. Ensure that no Ruby exception escapes from the VM. I guess there is an API like `rb_rescue2` and `rb_protect` [for that](https://silverhammermba.github.io/emberb/c/#rescue).

![rscript22unbindnameditemexc](https://cloud.githubusercontent.com/assets/2073329/21965074/72801be4-db58-11e6-8908-5aeba6137dd4.PNG)

**Comment by manison** [comment]
I modified the _activescriptruby.rb_ script distributed with the package to dump the exception from `remove_items` to a file and this is the output:

```
constant ActiveScriptRuby::GlobalProxy::Salamander not defined
  C:/Program Files (x86)/Ruby-2.4/lib/ruby/vendor_ruby/2.4.0/activescriptruby.rb:181:in `remove_const'
  C:/Program Files (x86)/Ruby-2.4/lib/ruby/vendor_ruby/2.4.0/activescriptruby.rb:181:in `delete_constant'
  C:/Program Files (x86)/Ruby-2.4/lib/ruby/vendor_ruby/2.4.0/activescriptruby.rb:175:in `remove_item'
  C:/Program Files (x86)/Ruby-2.4/lib/ruby/vendor_ruby/2.4.0/activescriptruby.rb:185:in `block in remove_items'
  C:/Program Files (x86)/Ruby-2.4/lib/ruby/vendor_ruby/2.4.0/activescriptruby.rb:185:in `each'
  C:/Program Files (x86)/Ruby-2.4/lib/ruby/vendor_ruby/2.4.0/activescriptruby.rb:185:in `remove_items'
```

**Comment by arton** [comment]
Thanks for your report.
I will investigate the issue on this weekend.

**Comment by arton** [comment]
I couldn't reproduce the issue.
However, I protected to call remove_items  from Ruby's exception by https://github.com/arton/RScript22/commit/00b5209e5541fae2418ad08d23333e03fa9158c7
