### ISSUE TITLE
Script does not execute when transferring to the CONNECTED state

### ISSUE THREAD

**Issue by manison** [arton/RScript22#7]
Our application may host any active script engine our users configure. With all engines we testes so far (particularly VBScript and JScript but also Perl, Python and PHP) it was enough to transfer the engine to the `CONNECTED` state to run the script. With this Ruby engine the script does not run until the engine is transferred to the `STARTED` state.

There is a list of a few sources that indicate setting the `CONNECTED` state should execute the script:

[Hosting – Running Scripts FAQ](http://e.craft.free.fr/ActiveScriptingLostFAQ/hostrun.htm)
> You need to create an instance of the engine you want (say VBScript) and then get its IActiveScript interface. Once that is done, you need to pass the script text to the engine and then move it to the CONNECTED state. This executes the script.

[Script Engine States](https://msdn.microsoft.com/en-us/library/xawadt95(v=vs.94).aspx#Anchor_1)
> connected: The script is loaded and connected for sinking events from host objects. If this is a transition from the initialized state, the scripting engine should transition through the started state, performing the necessary actions, before entering the connected state and connecting to events.

**Comment by arton** [comment]
Thank you for your kind report.
I'll fix it soon.

**Comment by arton** [comment]
fix by 17c64eb8ff0d1dd737b0fbd1d1ec6490ea61c039
