### ISSUE TITLE
hta doesn't work

### ISSUE THREAD

**Issue by dogatana** [arton/RScript22#9]
Hi, I installed Ruby-2.4.msi successfully, but failed to run holeb24.hta.

Since following codes show error, Windows does not recognize ActiveScritRuby.
Did I miss something?

```
'test1.vbs'
set r = CreateObject("ruby.object")
'test2.vbs'
set r = CreateObject("ruby.object.2.2")
'test3.vbs'
set r = CreateObject("ruby.object.2.4")

```
My Environment: Windows 7 64 bit.

**Comment by arton** [comment]
Because you use 64bit Windows, the default CScript/WScript are 64bit version and Ruby-2.4.msi installs 32bit ASR.
You should use C:\Windows\syswow64\CScript.exe or WScript.exe instead of c:\Windows\System32\CScript.exe or WScript.exe. Or installing Ruby-2.4-x64.msi.
Also, you may run MSHTA.exe in C:\Windows\Syswow64.

**Comment by dogatana** [comment]
Hi, thank you for your reply.
Now I understood.

Could you let me know how to change the default, if there is handy way?
I have some ruby scripts that drive Excel(32 bit) through win32ole, so I must use ruby-2.4(32 bit).
And I plan to distribute these scripts to other members with simple GUI by using hta.
I can change PATH setting on my PC, but it's hard to let others to do so.

I wish ruby 2.4 had Tk in it..

**Comment by arton** [comment]
I don't know handy way. 
However, I think it's possible to manipulate Excel 32 from Ruby 64 because they are separate process (say outer process) but connect with COM. 
https://msdn.microsoft.com/en-us/library/aa384203%28VS.85%29.aspx?f=255&MSPPError=-2147217396

**Comment by dogatana** [comment]
I appreciate your prompt reply.

Technically it may be possible.
But I could not use ruby64 to communicate with Exce32 through win32ole as far as I remember.

Windows and GUI is the hardest part of ruby life, sigh.

Thank you again for the advice!
